GEMINI_API_KEY = "YOUR_API_KEY_HERE"
GEMINI_MODEL = "gemini-2.0-flash"
TARGET_COIN = "bitcoin"
CURRENCY = "usd"
HISTORY_DAYS = 1
CRYPTOPANIC_TOKEN = "YOUR_CRYPTOPANIC_TOKEN_HERE"
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"
